Provide better feedback when destroying stack

diff --git a/bin/cfn b/bin/cfn
--- a/bin/cfn
+++ b/bin/cfn
@@ -53,10 +53,12 @@ function create_pipeline(){
 }
 
 function bucket_arns(){
+    set -e
     aws resourcegroupstaggingapi get-resources \
         --resource-type-filters="s3" \
         --tag-filters="Key=stack,Values=${STACK_NAME}" | \
-    jq '.ResourceTagMappingList[].ResourceARN' --raw-output
+    jq '.ResourceTagMappingList[].ResourceARN' --raw-output | \
+    sed -e 's/arn:aws:s3::://'
 }
 
 function disable_bucket_versioning(){
@@ -64,6 +66,7 @@ function disable_bucket_versioning(){
 }
 
 function delete_bucket_versions(){
+    set -e
     aws s3api list-object-versions --bucket="$1" |\
         jq '.Versions[], .DeleteMarkers[] | "\"\(.Key)\" \"\(.VersionId)\""' --raw-output |\
         awk -v bucket="$1" '{ \
@@ -76,28 +79,71 @@ function delete_bucket_versions(){
          }'
 }
 
-function delete_bucket(){
-    aws s3 rb --force "$1"
+function delete_stack(){
+    set -e
+    if aws cloudformation delete-stack --stack-name="$1"; then
+        tail_stack "$1"
+    fi
 }
 
-function delete_stack(){
-    aws cloudformation delete-stack \
-        --stack-name="${STACK_NAME}" | \
-    jq '.StackId' --raw-output
+function stack_events() {
+    # Borrowed from github.com/realestate-com-au/bash-my-aws
+    if output=$(aws cloudformation describe-stack-events \
+        --stack-name="$1" \
+        --query="
+          sort_by(StackEvents, &Timestamp)[].[
+            Timestamp,
+            LogicalResourceId,
+            ResourceType,
+            ResourceStatus
+          ]" \
+        --output=table); then
+        echo "$output" | uniq -u
+    else
+        return $?
+    fi
+}
+
+function tail_stack() {
+    # Borrowed from github.com/realestate-com-au/bash-my-aws
+    local stack="$1"
+    local current
+    local final_line
+    local output
+    local previous
+    until echo "$current" | tail -1 | grep -E -q "${stack}.*_(COMPLETE|FAILED)"
+    do
+        if ! output=$(stack-events "${stack}"); then
+            # Something went wrong with stack-events (like stack not known)
+            return 1
+        fi
+        if [ -z "$output" ]; then sleep 1; continue; fi
+
+        current=$(echo "$output" | sed '$d')
+        final_line=$(echo "$output" | tail -1)
+        if [ -z "$previous" ]; then
+            echo "$current"
+        elif [ "$current" != "$previous" ]; then
+            comm -13 <(echo "$previous") <(echo "$current")
+        fi
+        previous="$current"
+        sleep 1
+    done
+    echo $final_line
 }
 
 function destroy_resources(){
     arns="$(bucket_arns)"
     for arn in "$arns"; do
-        disable_bucket_versioning "$arn"
-        delete_bucket_versions "$arn"
-        delete_bucket "$arn"
+        if [ ! -z "$arn" ]; then
+            disable_bucket_versioning "$arn"
+            delete_bucket_versions "$arn"
+        fi
     done
-    # Delete stack
-    stack_id="$(delete_stack)"
-    # Wait for deletion to complete
-    aws cloudformation wait stack-delete-complete \
-        --stack-name="${stack_id}"
+    # Delete infra stack
+    delete_stack "${STACK_NAME}-production"
+    # Delete pipeline stack
+    delete_stack "${STACK_NAME}"
     # Delete log groups
     aws logs describe-log-groups \
         --log-group-name-prefix="/aws/lambda/${APP_NAME}" | \
